version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

clash_rule_base="https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml"


[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—", ".*"]
[[custom_groups]]
name = "âœˆ æ‰‹åŠ¨é€‰æ‹©"
type = "select"
rule = ["[]DIRECT", "[]REJECT", "âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—", ".*"]
[[custom_groups]]
name = "âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
url = "http://www.google.com/generate_204"
interval = "300"
strategy = "round-robin"
rule = [".*"]
[[custom_groups]]
name = "âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"
type = "load-balance"
url = "http://www.google.com/generate_204"
interval = "300"
strategy = "consistent-hashing"
rule = [".*"]
[[custom_groups]]
name = "ğŸ›¹ CloudFlareç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "âš¡ MegaUpç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ€„ Cç«™ç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ›‘ shareå¾®äº‘ARMå¼¹çª—"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ’® æ¼«ç”»ç›´è¿,"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸŒ¸ æ¼«ç”»ä»£ç†"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸƒ è‡ªå®šç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ”° è‡ªå®šä»£ç†"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ¥ NETFLIX"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "(Netflix|NF)", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "(å°)", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ§¿ GoogleCN"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯Bing"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ’¬ OpenAi"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]DIRECT", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸƒ åº”ç”¨å‡€åŒ–"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª-å¹¿å‘Šè”ç›Ÿ"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª-åº”ç”¨å¹¿å‘Š"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]
[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª-EeasyList"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]âœˆ æ‰‹åŠ¨é€‰æ‹©", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"]




# short names

[[rename_node]]
match = "å¾å·"
replace = "å¾"
[[rename_node]]
match = "æ·±åœ³"
replace = "æ·±"
[[rename_node]]
match = "ä¸Šæµ·"
replace = "æ²ª"
[[rename_node]]
match = "å¹¿å·"
replace = "ç©—"
[[rename_node]]
match = "å®æ³¢"
replace = "ç”¬"
[[rename_node]]
match = "è´µé˜³"
replace = "ç­‘"
[[rename_node]]
match = "æ­¦æ±‰"
replace = "æ±‰"
[[rename_node]]
match = "å—äº¬"
replace = "å®"
[[rename_node]]
match = "å¤©æ´¥"
replace = "æ´¥"
[[rename_node]]
match = "åŒ—äº¬"
replace = "äº¬"
[[rename_node]]
match = "æ²ˆé˜³"
replace = "æ²ˆ"
[[rename_node]]
match = "æ±Ÿè‹"
replace = "è‹"
[[rename_node]]
match = "æµ™æ±Ÿ"
replace = "æµ™"
[[rename_node]]
match = "å®‰å¾½"
replace = "çš–"
[[rename_node]]
match = "ç¦å»º"
replace = "é—½"
[[rename_node]]
match = "æ¹–å—"
replace = "æ¹˜"
[[rename_node]]
match = "å¹¿ä¸œ"
replace = "ç²¤"
[[rename_node]]
match = "æµ·å—"
replace = "ç¼"
[[rename_node]]
match = "å››å·"
replace = "å·"
[[rename_node]]
match = "è´µå·"
replace = "è´µ"
[[rename_node]]
match = "äº‘å—"
replace = "äº‘"
[[rename_node]]
match = "é’æµ·"
replace = "é’"
[[rename_node]]
match = "å°æ¹¾"
replace = "å°"
[[rename_node]]
match = "é¦™æ¸¯"
replace = "æ¸¯"
[[rename_node]]
match = "æ¾³é—¨"
replace = "æ¾³"
[[rename_node]]
match = "ç¾å›½"
replace = "ç¾"
[[rename_node]]
match = "è‹±å›½"
replace = "è‹±"
[[rename_node]]
match = "åŠ æ‹¿å¤§"
replace = "åŠ "
[[rename_node]]
match = "æ³•å›½"
replace = "æ³•"
[[rename_node]]
match = "å¾·å›½"
replace = "å¾·"
[[rename_node]]
match = "ç‘å£«"
replace = "ç‘"
[[rename_node]]
match = "æ—¥æœ¬"
replace = "æ—¥"
[[rename_node]]
match = "éŸ©å›½"
replace = "éŸ©"
[[rename_node]]
match = "èŠ¬å…°"
replace = "èŠ¬"
[[rename_node]]
match = "å°åº¦"
replace = "å°"
[[rename_node]]
match = "æ³°å›½"
replace = "æ³°"
[[rename_node]]
match = "è¶Šå—"
replace = "è¶Š"
[[rename_node]]
match = "æ–°åŠ å¡"
replace = "æ–°"
[[rename_node]]
match = "æ„å¤§åˆ©"
replace = "æ„"
[[rename_node]]
match = "è²å¾‹å®¾"
replace = "è²"
[[rename_node]]
match = "ä¿„ç½—æ–¯"
replace = "ä¿„"
[[rename_node]]
match = "åœŸè€³å…¶"
replace = "åœŸ"

# times RE
#[[rename_node]]
#match = '\(?((x|X)?(\d+)(\.?\d+)?)((\s?å€ç‡?)|(x|X))\)?'
#replace = "$1x"
