# HTTP 代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# Linux 和 macOS 的 redir 代理端口
redir-port: 7892
# 允许局域网的连接
allow-lan: true
# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule
# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info
# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'
secret: ''
cfw-bypass:
  # 直连列表
  - "*.cn"
  # 中国国内常见域名关键词直连
  - "*-cn*"
  - "*360buy*"
  - "*alimama*"
  - "*alipay*"
  - "*appzapp*"
  - "*baidupcs*"
  - "*bilibili*"
  - "*ccgslb*"
  - "*chinacache*"
  - "*duobao*"
  - "*duolingo*"
  - "*jdpay*"
  - "*moke*"
  - "*qhimg*"
  - "*vpimg*"
  - "*xiami*"
  - "*xiaomi*"
  # 360
  - "*.360.com"
  - "*.360kuai.com"
  - "*.360safe.com"
  - "*.qhres.com"
  - "*.qhstatic.com"
  # 4399
  - "*.4399.com"
  - "*.4399pk.com"
  - "*.5054399.com"
  - "*.img4399.com"
  # 58
  - "*.58.com"
  # Alibaba
  - "*.aliapp.org"
  - "*.alibaba.com"
  - "*.alibabacloud.com"
  - "*.alicdn.com"
  - "*.aliexpress.com"
  - "*.aliimg.com"
  - "*.alikunlun.com"
  - "*.alipay.com"
  - "*.alipayobjects.com"
  - "*.alisoft.com"
  - "*.aliyun.com"
  - "*.aliyuncdn.com"
  - "*.aliyuncs.com"
  - "*.amap.com"
  - "*.autonavi.com"
  - "*.dingtalk.com"
  - "*.hichina.com"
  - "*.mmstat.com"
  - "*.mxhichina.com"
  - "*.soku.com"
  - "*.taobao.com"
  - "*.taobaocdn.com"
  - "*.tbcache.com"
  - "*.tbcdn.com"
  - "*.tmall.com"
  - "*.tmall.hk"
  - "*.xiami.com"
  - "*.xiami.net"
  - "*.ykimg.com"
  - "*.youku.com"
  # Apple
  - "*.aaplimg.com"
  - "*.akadns.net"
  - "*.apple-cloudkit.com"
  - "*.apple.co"
  - "*.apple.com"
  - "*.appstore.com"
  - "*.cdn-apple.com"
  - "*.crashlytics.com"
  - "*.icloud-content.com"
  - "*.icloud.com"
  - "*.me.com"
  - "*.mzstatic.com"
  # Baidu
  - "*.baidu.com"
  - "*.baidubcr.com"
  - "*.baidupcs.com"
  - "*.baidustatic.com"
  - "*.bcebos.com"
  - "*.bdstatic.com"
  - "*.hao123.com"
  - "*.hao123img.com"
  - "*.iqiyi.com"
  - "*.iqiyipic.com"
  - "*.jomodns.com"
  - "*.yunjiasu-cdn.net"
  # Bilibili
  - "*.acg.tv"
  - "*.acgvideo.com"
  - "*.b23.tv"
  - "*.biliapi.com"
  - "*.biliapi.net"
  - "*.bilibili.com"
  - "*.bilibili.tv"
  - "*.biligame.com"
  - "*.biligame.net"
  - "*.hdslb.com"
  - "*.im9.com"
  # Blizzard
  - "*.battle.net"
  - "*.battlenet.com"
  - "*.blizzard.com"
  # ByteDance
  - "*.bytecdn.cn"
  - "*.bytedance.com"
  - "*.feiliao.com"
  - "*.iesdouyin.com"
  - "*.pstatp.com"
  - "*.snssdk.com"
  - "*.toutiao.com"
  # CCTV
  - "*.cctv.com"
  - "*.cctvpic.com"
  - "*.livechina.com"
  # ChinaNet
  - "*.21cn.com"
  # DiDi
  - "*.didialift.com"
  - "*.didiglobal.com"
  - "*.udache.com"
  # Epic
  - "*.epicgames.com"
  - "*.helpshift.com"
  - "*.paragon.com"
  - "*.unrealengine.com"
  # HuaWei
  - "*.dbankcdn.com"
  - "*.hc-cdn.com"
  - "*.hicloud.com"
  - "*.huawei.com"
  - "*.huaweicloud.com"
  - "*.huaweishop.net"
  - "*.hwccpc.com"
  - "*.vmall.com"
  - "*.vmallres.com"
  # Iflytek 科大讯飞
  - "*.iflyink.com"
  - "*.iflyrec.com"
  - "*.iflytek.com"
  # JD
  - "*.360buyimg.com"
  - "*.jdcloud.com"
  - "*.jcloudcs.com"
  - "*.jd.com"
  - "*.jd.hk"
  - "*.jdpay.com"
  # Kingsoft
  - "*.iciba.com"
  - "*.ksosoft.com"
  - "*.ksyun.com"
  # Meitu
  - "*.meitu.com"
  - "*.meitudata.com"
  - "*.meitustat.com"
  - "*.meipai.com"
  # MI
  - "*.duokan.com"
  - "*.mi-img.com"
  - "*.miui.com"
  - "*.miwifi.com"
  - "*.xiaomi.com"
  # Microsoft
  - "*.microsoft.com"
  - "*.msecnd.net"
  - "*.office365.com"
  - "*.outlook.com"
  - "*.s-microsoft.com"
  - "*.visualstudio.com"
  - "*.windows.com"
  - "*.windowsupdate.com"
  # NetEase
  - "*.126.net"
  - "*.127.net"
  - "*.163.com"
  - "*.163yun.com"
  - "*.lofter.com"
  - "*.netease.com"
  - "*.ydstatic.com"
  - "*.youdao.com"
  # Sina
  - "*.miaopai.com"
  - "*.sina.cn"
  - "*.sina.com"
  - "*.sina.com.cn"
  - "*.sinaapp.com"
  - "*.sinaimg.cn"
  - "*.sinaimg.com"
  - "*.sinajs.cn"
  - "*.t.cn"
  - "*.weibo.com"
  - "*.weibocdn.com"
  - "*.xiaoka.tv"
  # Sohu Sogo
  - "*.itc.cn"
  - "*.sogo.com"
  - "*.sogou.com"
  - "*.sogoucdn.com"
  - "*.sohu-inc.com"
  - "*.sohu.com"
  - "*.sohucs.com"
  - "*.sohuno.com"
  - "*.sohurdc.com"
  - "*.v-56.com"
  # Sony
  - "*.playstation.com"
  - "*.playstation.net"
  - "*.playstationnetwork.com"
  - "*.sony.com"
  - "*.sonyentertainmentnetwork.com"
  # Spark
  - "*.amplitude.com"
  - "*.firebaseio.com"
  - "*.hockeyapp.net"
  - "*.smartmailcloud.com"
  # Steam
  - "*.steampowered.com"
  - "*.steam-chat.com"
  - "*.steamgames.com"
  - "*.steamusercontent.com"
  - "*.steamcontent.com"
  - "*.steamstatic.com"
  - "*.steamcdn-a.akamaihd.net"
  - "*.steamstat.us"
  # Tencent
  - "*.gtimg.cn"
  - "*.gtimg.com"
  - "*.idqqimg.com"
  - "*.igamecj.com"
  - "*.myapp.com"
  - "*.myqcloud.com"
  - "*.qlogo.cn"
  - "*.qpic.cn"
  - "*.qq.com"
  - "*.qqmail.com"
  - "*.qtimg.cn"
  - "*.smtcdns.com"
  - "*.soso.com"
  - "*.tencent-cloud.net"
  - "*.tencent.com"
  - "*.tencentmind.com"
  - "*.weixin.com"
  - "*.weiyun.com"
  # Vip
  - "*.appsimg.com"
  - "*.appvipshop.com"
  - "*.vip.com"
  - "*.vipstatic.com"
  # YYeTs
  - "*.jstucdn.com"
  - "*.zimuzu.io"
  - "*.zimuzu.tv"
  - "*.zmz2019.com"
  - "*.zmzapi.com"
  - "*.zmzapi.net"
  - "*.zmzfile.com"
  # Yonyou
  - "*.yonyou.com"
  - "*.yonyoucloud.com"
  - "*.shufafin.com"
  # Acceleratedirectsites
  - "*.12306.com"
  - "*.126.com"
  - "*.1688.com"
  - "*.17k.com"
  - "*.360.com"
  - "*.360buy.com"
  - "*.360doc.com"
  - "*.360safe.com"
  - "*.36kr.com"
  - "*.51job.com"
  - "*.51jobcdn.com"
  - "*.56.com"
  - "*.abercrombie.com"
  - "*.acfun.tv"
  - "*.air-matters.com"
  - "*.air-matters.io"
  - "*.algocasts.io"
  - "*.apache.org"
  - "*.bdimg.com"
  - "*.bing.com"
  - "*.biqudu.com"
  - "*.biquge.com"
  - "*.bitauto.com"
  - "*.bootcss.com"
  - "*.c-ctrip.com"
  - "*.camera360.com"
  - "*.che168.com"
  - "*.chinacache.net"
  - "*.chinaso.com"
  - "*.chinaz.com"
  - "*.cibntv.net"
  - "*.clouddn.com"
  - "*.cloudxns.net"
  - "*.cmfu.com"
  - "*.cn163.net"
  - "*.cnbeta.com"
  - "*.cnbetacdn.com"
  - "*.coolapk.com"
  - "*.coolapkmarket.com"
  - "*.csdn.net"
  - "*.ctrip.com"
  - "*.dangdang.com"
  - "*.dfcfw.com"
  - "*.dianping.com"
  - "*.dilidili.wang"
  - "*.douban.com"
  - "*.doubanio.com"
  - "*.douyu.com"
  - "*.dytt8.net"
  - "*.easou.com"
  - "*.eastmoney.com"
  - "*.ecitic.com"
  - "*.ewqcxz.com"
  - "*.fang.com"
  - "*.fantasy.tv"
  - "*.feng.com"
  - "*.fengkongcloud.com"
  - "*.fir.im"
  - "*.firefox.com"
  - "*.frdic.com"
  - "*.fresh-ideas.cc"
  - "*.geetest.com"
  - "*.godic.net"
  - "*.gravatar.com"
  - "*.guazi.com"
  - "*.gwdang.com"
  - "*.gzlzfm.com"
  - "*.haibian.com"
  - "*.haosou.com"
  - "*.hollisterco.com"
  - "*.hongxiu.com"
  - "*.huajiao.com"
  - "*.hupu.com"
  - "*.huya.com"
  - "*.ifeng.com"
  - "*.ifengimg.com"
  - "*.images-amazon.com"
  - "*.infzm.com"
  - "*.ipip.net"
  - "*.it168.com"
  - "*.ithome.com"
  - "*.ixdzs.com"
  - "*.jianguoyun.com"
  - "*.jianshu.com"
  - "*.jianshu.io"
  - "*.jianshuapi.com"
  - "*.jiathis.com"
  - "*.jumei.com"
  - "*.kanimg.com"
  - "*.kankan.com"
  - "*.kaola.com"
  - "*.knewone.com"
  - "*.kuaidi100.com"
  - "*.kugou.com"
  - "*.lancdns.com"
  - "*.landiannews.com"
  - "*.le.com"
  - "*.lecloud.com"
  - "*.lemicp.com"
  - "*.letitfly.me"
  - "*.letv.com"
  - "*.letvcloud.com"
  - "*.linkedin.com"
  - "*.lizhi.fm"
  - "*.lizhi.io"
  - "*.lizhifm.com"
  - "*.loli.net"
  - "*.luoo.net"
  - "*.lvmama.com"
  - "*.lxdns.com"
  - "*.meituan.com"
  - "*.meituan.net"
  - "*.meizu.com"
  - "*.mi.com"
  - "*.mobike.com"
  - "*.moji.com"
  - "*.moke.com"
  - "*.mubu.com"
  - "*.myunlu.com"
  - "*.nruan.com"
  - "*.nuomi.com"
  - "*.oracle.com"
  - "*.oschina.net"
  - "*.ourdvs.com"
  - "*.overcast.fm"
  - "*.paypal.com"
  - "*.pptv.com"
  - "*.qbox.me"
  - "*.qcloud.com"
  - "*.qdaily.com"
  - "*.qdmm.com"
  - "*.qhimg.com"
  - "*.qidian.com"
  - "*.qihucdn.com"
  - "*.qin.io"
  - "*.qiniu.com"
  - "*.qiniucdn.com"
  - "*.qiniudn.com"
  - "*.qiushibaike.com"
  - "*.qiyi.com"
  - "*.qiyipic.com"
  - "*.qqurl.com"
  - "*.quanmin.tv"
  - "*.qunar.com"
  - "*.rarbg.to"
  - "*.repaik.com"
  - "*.rrmj.tv"
  - "*.ruguoapp.com"
  - "*.sandai.net"
  - "*.shumilou.net"
  - "*.simplecd.me"
  - "*.sm.ms"
  - "*.smtcdns.net"
  - "*.smzdm.com"
  - "*.snwx.com"
  - "*.so.com"
  - "*.ssl-images-amazon.com"
  - "*.sspai.com"
  - "*.startssl.com"
  - "*.suning.com"
  - "*.tenpay.com"
  - "*.th-sjy.com"
  - "*.tianyancha.com"
  - "*.tietuku.com"
  - "*.tiexue.net"
  - "*.tmiaoo.com"
  - "*.trip.com"
  - "*.ttmeiju.com"
  - "*.tudou.com"
  - "*.tuniu.com"
  - "*.upaiyun.com"
  - "*.upyun.com"
  - "*.uxengine.net"
  - "*.v2ex.com"
  - "*.vmware.com"
  - "*.wandoujia.com"
  - "*.weather.com"
  - "*.weico.cc"
  - "*.weidian.com"
  - "*.weiphone.com"
  - "*.weiphone.net"
  - "*.xdrig.com"
  - "*.xiaojukeji.com"
  - "*.xiaomi.net"
  - "*.xiaomicp.com"
  - "*.ximalaya.com"
  - "*.xinhuanet.com"
  - "*.xitek.com"
  - "*.xiumi.us"
  - "*.xmcdn.com"
  - "*.xslb.net"
  - "*.xunlei.com"
  - "*.yach.me"
  - "*.yangkeduo.com"
  - "*.yeepay.com"
  - "*.yhd.com"
  - "*.yinxiang.com"
  - "*.yinyuetai.com"
  - "*.yixia.com"
  - "*.ys168.com"
  - "*.yy.com"
  - "*.zdfans.com"
  - "*.zealer.com"
  - "*.zhangzishi.cc"
  - "*.zhanqi.tv"
  - "*.zhaopin.com"
  - "*.zhihu.com"
  - "*.zhimg.com"
  - "*.zhongsou.com"
  - "*.zhuihd.com"
  - "*.zmz001.com"
  - "*.zmz002.com"
  - "*.zmz003.com"
  - "*.zmz004.com"
  - "localhost"
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
# 打断连接
cfw-conn-break-strategy:
  proxy: none              # none/chain/all
  profile: true            # true/false
  mode: false              # true/false
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'
# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder
#dns:
#  enable: true
#  ipv6: false
#  listen: 0.0.0.0:53
#  enhanced-mode: redir-host
#  nameserver:
#     - 117.50.10.10
#     - 114.114.114.114
#     - 119.29.29.29
#     - 180.76.76.76
#     - 1.2.4.8
#     - 223.5.5.5
#     - 8.8.8.8
#  fallback:
#     - tls://dns.rubyfish.cn:853
#     - tls://1.0.0.1:853
#     - tls://dns.google:853
# Clash for Windows